#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-pillar
Version  : 1.4.2
Release  : 29
URL      : https://cran.r-project.org/src/contrib/pillar_1.4.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/pillar_1.4.2.tar.gz
Summary  : Coloured Formatting for Columns
Group    : Development/Tools
License  : GPL-3.0
Requires: R-cli
Requires: R-crayon
Requires: R-fansi
Requires: R-rlang
Requires: R-utf8
Requires: R-vctrs
BuildRequires : R-cli
BuildRequires : R-crayon
BuildRequires : R-fansi
BuildRequires : R-rlang
BuildRequires : R-utf8
BuildRequires : R-vctrs
BuildRequires : buildreq-R

%description
of data using the full range of colours provided by modern terminals.

%prep
%setup -q -c -n pillar

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1562205975

%install
export SOURCE_DATE_EPOCH=1562205975
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library pillar
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library pillar
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library pillar
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc pillar || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/pillar/DESCRIPTION
/usr/lib64/R/library/pillar/INDEX
/usr/lib64/R/library/pillar/Meta/Rd.rds
/usr/lib64/R/library/pillar/Meta/features.rds
/usr/lib64/R/library/pillar/Meta/hsearch.rds
/usr/lib64/R/library/pillar/Meta/links.rds
/usr/lib64/R/library/pillar/Meta/nsInfo.rds
/usr/lib64/R/library/pillar/Meta/package.rds
/usr/lib64/R/library/pillar/NAMESPACE
/usr/lib64/R/library/pillar/NEWS.md
/usr/lib64/R/library/pillar/R/pillar
/usr/lib64/R/library/pillar/R/pillar.rdb
/usr/lib64/R/library/pillar/R/pillar.rdx
/usr/lib64/R/library/pillar/help/AnIndex
/usr/lib64/R/library/pillar/help/aliases.rds
/usr/lib64/R/library/pillar/help/figures/colours.png
/usr/lib64/R/library/pillar/help/figures/lifecycle-archived.svg
/usr/lib64/R/library/pillar/help/figures/lifecycle-defunct.svg
/usr/lib64/R/library/pillar/help/figures/lifecycle-deprecated.svg
/usr/lib64/R/library/pillar/help/figures/lifecycle-experimental.svg
/usr/lib64/R/library/pillar/help/figures/lifecycle-maturing.svg
/usr/lib64/R/library/pillar/help/figures/lifecycle-questioning.svg
/usr/lib64/R/library/pillar/help/figures/lifecycle-soft-deprecated.svg
/usr/lib64/R/library/pillar/help/figures/lifecycle-stable.svg
/usr/lib64/R/library/pillar/help/paths.rds
/usr/lib64/R/library/pillar/help/pillar.rdb
/usr/lib64/R/library/pillar/help/pillar.rdx
/usr/lib64/R/library/pillar/html/00Index.html
/usr/lib64/R/library/pillar/html/R.css
/usr/lib64/R/library/pillar/tests/testthat.R
/usr/lib64/R/library/pillar/tests/testthat/bw-out/asis-list.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/asis-number.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/basic-signif-5.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/basic-signif-7.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/basic-slightly-nonint.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/basic.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/date.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/deal1.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/deal2.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/deal3.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/decimal-insignif.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/difftime.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/escaped.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/factor.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/integer-06.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/integer-07.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/integer-08.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/integer-09.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/letters-inf.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/letters-long-03.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/letters-long-10.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/letters-long.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/letters.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/list-each.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/list-na.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/list-narrow.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/list-null.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/logical.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/lubridate.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/matrix-col-empty.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/matrix-col-named.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/matrix-col.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-04.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-05.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-06.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-07.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-08.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-09.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-10.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-11.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-12.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-13.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-14.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-15.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-16.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-17.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-18.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-19.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-20.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-21.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-22.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-23.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-24.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-25.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-26.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-27.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-28.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-29.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-30.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-31.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-32.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-33.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-34.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-35.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-36.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-37.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-38.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-39.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-extra-10.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-extra-20.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-extra-30.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-extra-35.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-extra-40.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/multi-inf.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/na-names.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/numeric-04.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/numeric-07.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/numeric-10.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/numeric-15.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/numeric-22.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/ordered.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/rowid-3.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/rowid-star-title-12.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/scientific-short-neg.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/scientific-tiny.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/scientific.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/sep.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/spaces.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-01-1382-59.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-02-837-54.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-03-455-32.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-04-855-55.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-05-552-54.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-06-1031-49.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-07-429-38.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-08-633-54.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-09-1496-39.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-10-493-31.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-11-1130-52.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-12-1310-58.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-13-484-47.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-14-779-55.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-15-694-46.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-16-516-54.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-17-1365-42.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-18-934-39.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-19-565-32.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-20-1121-35.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-21-446-32.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-22-1166-31.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-23-546-58.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-24-1035-57.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-25-1217-33.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-26-770-32.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-27-1439-46.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-28-1065-52.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-29-393-35.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/str-30-999-41.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/style-bold-false.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/style-neg-false.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/style-regular.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/style-subtle-false.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/style-subtle-neg-false.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/style-subtle-num-true.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-all--30.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-all--300-20.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-all--300-30.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-all--300-40.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-all--300-50.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-all--300-60.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-all--300-70.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-all--300.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-col-empty.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-col-nested.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-col.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-iris-3-20.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-iris-5-30.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-mtcars-8-30.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-newline.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-non-syntactic.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/tibble-space.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/time-digits-secs.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/time-posix.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/time.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/title-crayon.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/title-fifteen.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/title-longer.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/title-none.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/title-short.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/title-too-long.txt
/usr/lib64/R/library/pillar/tests/testthat/bw-out/utf8.txt
/usr/lib64/R/library/pillar/tests/testthat/helper-output.R
/usr/lib64/R/library/pillar/tests/testthat/out-native/asis-list.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/asis-number.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/basic-signif-5.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/basic-signif-7.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/basic-slightly-nonint.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/basic.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/date.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/deal1.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/deal2.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/deal3.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/decimal-insignif.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/difftime.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/escaped.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/factor.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/integer-06.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/integer-07.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/integer-08.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/integer-09.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/letters-inf.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/letters-long-03.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/letters-long-10.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/letters-long.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/letters.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/list-each.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/list-na.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/list-narrow.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/list-null.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/logical.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/lubridate.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/matrix-col-empty.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/matrix-col-named.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/matrix-col.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-04.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-05.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-06.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-07.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-08.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-09.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-10.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-11.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-12.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-13.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-14.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-15.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-16.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-17.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-18.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-19.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-20.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-21.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-22.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-23.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-24.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-25.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-26.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-27.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-28.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-29.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-30.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-31.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-32.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-33.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-34.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-35.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-36.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-37.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-38.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-39.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-extra-10.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-extra-20.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-extra-30.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-extra-35.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-extra-40.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/multi-inf.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/na-names.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/numeric-04.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/numeric-07.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/numeric-10.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/numeric-15.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/numeric-22.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/ordered.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/rowid-3.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/rowid-star-title-12.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/scientific-short-neg.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/scientific-tiny.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/scientific.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/sep.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/spaces.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-01-1382-59.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-02-837-54.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-03-455-32.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-04-855-55.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-05-552-54.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-06-1031-49.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-07-429-38.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-08-633-54.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-09-1496-39.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-10-493-31.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-11-1130-52.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-12-1310-58.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-13-484-47.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-14-779-55.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-15-694-46.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-16-516-54.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-17-1365-42.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-18-934-39.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-19-565-32.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-20-1121-35.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-21-446-32.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-22-1166-31.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-23-546-58.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-24-1035-57.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-25-1217-33.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-26-770-32.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-27-1439-46.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-28-1065-52.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-29-393-35.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/str-30-999-41.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/style-bold-false.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/style-neg-false.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/style-regular.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/style-subtle-false.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/style-subtle-neg-false.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/style-subtle-num-true.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-all--30.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-all--300-20.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-all--300-30.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-all--300-40.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-all--300-50.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-all--300-60.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-all--300-70.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-all--300.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-col-empty.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-col-nested.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-col.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-iris-3-20.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-iris-5-30.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-mtcars-8-30.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-newline.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-non-syntactic.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/tibble-space.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/time-digits-secs.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/time-posix.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/time.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/title-crayon.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/title-fifteen.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/title-longer.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/title-none.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/title-short.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/title-too-long.txt
/usr/lib64/R/library/pillar/tests/testthat/out-native/utf8.txt
/usr/lib64/R/library/pillar/tests/testthat/out/asis-list.txt
/usr/lib64/R/library/pillar/tests/testthat/out/asis-number.txt
/usr/lib64/R/library/pillar/tests/testthat/out/basic-signif-5.txt
/usr/lib64/R/library/pillar/tests/testthat/out/basic-signif-7.txt
/usr/lib64/R/library/pillar/tests/testthat/out/basic-slightly-nonint.txt
/usr/lib64/R/library/pillar/tests/testthat/out/basic.txt
/usr/lib64/R/library/pillar/tests/testthat/out/date.txt
/usr/lib64/R/library/pillar/tests/testthat/out/deal1.txt
/usr/lib64/R/library/pillar/tests/testthat/out/deal2.txt
/usr/lib64/R/library/pillar/tests/testthat/out/deal3.txt
/usr/lib64/R/library/pillar/tests/testthat/out/decimal-insignif.txt
/usr/lib64/R/library/pillar/tests/testthat/out/difftime.txt
/usr/lib64/R/library/pillar/tests/testthat/out/escaped.txt
/usr/lib64/R/library/pillar/tests/testthat/out/factor.txt
/usr/lib64/R/library/pillar/tests/testthat/out/integer-06.txt
/usr/lib64/R/library/pillar/tests/testthat/out/integer-07.txt
/usr/lib64/R/library/pillar/tests/testthat/out/integer-08.txt
/usr/lib64/R/library/pillar/tests/testthat/out/integer-09.txt
/usr/lib64/R/library/pillar/tests/testthat/out/letters-inf.txt
/usr/lib64/R/library/pillar/tests/testthat/out/letters-long-03.txt
/usr/lib64/R/library/pillar/tests/testthat/out/letters-long-10.txt
/usr/lib64/R/library/pillar/tests/testthat/out/letters-long.txt
/usr/lib64/R/library/pillar/tests/testthat/out/letters.txt
/usr/lib64/R/library/pillar/tests/testthat/out/list-each.txt
/usr/lib64/R/library/pillar/tests/testthat/out/list-na.txt
/usr/lib64/R/library/pillar/tests/testthat/out/list-narrow.txt
/usr/lib64/R/library/pillar/tests/testthat/out/list-null.txt
/usr/lib64/R/library/pillar/tests/testthat/out/list-one.txt
/usr/lib64/R/library/pillar/tests/testthat/out/logical.txt
/usr/lib64/R/library/pillar/tests/testthat/out/lubridate.txt
/usr/lib64/R/library/pillar/tests/testthat/out/matrix-col-empty.txt
/usr/lib64/R/library/pillar/tests/testthat/out/matrix-col-named.txt
/usr/lib64/R/library/pillar/tests/testthat/out/matrix-col.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-04.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-05.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-06.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-07.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-08.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-09.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-10.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-11.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-12.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-13.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-14.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-15.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-16.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-17.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-18.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-19.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-20.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-21.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-22.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-23.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-24.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-25.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-26.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-27.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-28.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-29.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-30.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-31.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-32.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-33.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-34.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-35.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-36.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-37.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-38.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-39.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-extra-10.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-extra-20.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-extra-30.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-extra-35.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-extra-40.txt
/usr/lib64/R/library/pillar/tests/testthat/out/multi-inf.txt
/usr/lib64/R/library/pillar/tests/testthat/out/na-names.txt
/usr/lib64/R/library/pillar/tests/testthat/out/numeric-04.txt
/usr/lib64/R/library/pillar/tests/testthat/out/numeric-07.txt
/usr/lib64/R/library/pillar/tests/testthat/out/numeric-10.txt
/usr/lib64/R/library/pillar/tests/testthat/out/numeric-15.txt
/usr/lib64/R/library/pillar/tests/testthat/out/numeric-22.txt
/usr/lib64/R/library/pillar/tests/testthat/out/ordered.txt
/usr/lib64/R/library/pillar/tests/testthat/out/rowid-3.txt
/usr/lib64/R/library/pillar/tests/testthat/out/rowid-star-title-12.txt
/usr/lib64/R/library/pillar/tests/testthat/out/scientific-short-neg.txt
/usr/lib64/R/library/pillar/tests/testthat/out/scientific-tiny.txt
/usr/lib64/R/library/pillar/tests/testthat/out/scientific.txt
/usr/lib64/R/library/pillar/tests/testthat/out/sep.txt
/usr/lib64/R/library/pillar/tests/testthat/out/spaces.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-01-1382-59.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-02-837-54.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-03-455-32.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-04-855-55.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-05-552-54.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-06-1031-49.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-07-429-38.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-08-633-54.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-09-1496-39.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-10-493-31.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-11-1130-52.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-12-1310-58.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-13-484-47.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-14-779-55.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-15-694-46.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-16-516-54.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-17-1365-42.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-18-934-39.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-19-565-32.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-20-1121-35.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-21-446-32.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-22-1166-31.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-23-546-58.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-24-1035-57.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-25-1217-33.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-26-770-32.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-27-1439-46.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-28-1065-52.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-29-393-35.txt
/usr/lib64/R/library/pillar/tests/testthat/out/str-30-999-41.txt
/usr/lib64/R/library/pillar/tests/testthat/out/style-bold-false.txt
/usr/lib64/R/library/pillar/tests/testthat/out/style-neg-false.txt
/usr/lib64/R/library/pillar/tests/testthat/out/style-regular.txt
/usr/lib64/R/library/pillar/tests/testthat/out/style-subtle-false.txt
/usr/lib64/R/library/pillar/tests/testthat/out/style-subtle-neg-false.txt
/usr/lib64/R/library/pillar/tests/testthat/out/style-subtle-num-true.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-all--30.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-all--300-20.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-all--300-30.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-all--300-40.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-all--300-50.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-all--300-60.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-all--300-70.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-all--300.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-all-digits-secs.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-col-empty.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-col-nested.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-col.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-iris-3-20.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-iris-5-30.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-mtcars-8-30.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-newline.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-non-syntactic.txt
/usr/lib64/R/library/pillar/tests/testthat/out/tibble-space.txt
/usr/lib64/R/library/pillar/tests/testthat/out/time-digits-secs.txt
/usr/lib64/R/library/pillar/tests/testthat/out/time-posix.txt
/usr/lib64/R/library/pillar/tests/testthat/out/time.txt
/usr/lib64/R/library/pillar/tests/testthat/out/title-crayon.txt
/usr/lib64/R/library/pillar/tests/testthat/out/title-fifteen.txt
/usr/lib64/R/library/pillar/tests/testthat/out/title-longer.txt
/usr/lib64/R/library/pillar/tests/testthat/out/title-none.txt
/usr/lib64/R/library/pillar/tests/testthat/out/title-short.txt
/usr/lib64/R/library/pillar/tests/testthat/out/title-too-long.txt
/usr/lib64/R/library/pillar/tests/testthat/out/utf8.txt
/usr/lib64/R/library/pillar/tests/testthat/test-aaa.R
/usr/lib64/R/library/pillar/tests/testthat/test-dim.R
/usr/lib64/R/library/pillar/tests/testthat/test-distribute.R
/usr/lib64/R/library/pillar/tests/testthat/test-format_asis.R
/usr/lib64/R/library/pillar/tests/testthat/test-format_character.R
/usr/lib64/R/library/pillar/tests/testthat/test-format_date.R
/usr/lib64/R/library/pillar/tests/testthat/test-format_decimal.R
/usr/lib64/R/library/pillar/tests/testthat/test-format_factor.R
/usr/lib64/R/library/pillar/tests/testthat/test-format_integer.R
/usr/lib64/R/library/pillar/tests/testthat/test-format_list.R
/usr/lib64/R/library/pillar/tests/testthat/test-format_logical.R
/usr/lib64/R/library/pillar/tests/testthat/test-format_lubridate.R
/usr/lib64/R/library/pillar/tests/testthat/test-format_multi.R
/usr/lib64/R/library/pillar/tests/testthat/test-format_numeric.R
/usr/lib64/R/library/pillar/tests/testthat/test-format_rowid.R
/usr/lib64/R/library/pillar/tests/testthat/test-format_scientific.R
/usr/lib64/R/library/pillar/tests/testthat/test-format_time.R
/usr/lib64/R/library/pillar/tests/testthat/test-new-pillar-title.R
/usr/lib64/R/library/pillar/tests/testthat/test-new-pillar-type.R
/usr/lib64/R/library/pillar/tests/testthat/test-obj-sum.R
/usr/lib64/R/library/pillar/tests/testthat/test-ticks.R
/usr/lib64/R/library/pillar/tests/testthat/test-title.R
